[package]
name = "chessterm"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
ratatui = "0.27.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
tokio-util = "0.7.11"
